name: Go Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build binaries
        run: make all

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            v6-proxy-linux-amd64
            v6-proxy-linux-arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            v6-proxy-linux-amd64
            v6-proxy-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
